services:
  web:
    build: .
    container_name: saasflow_web
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: saasflow_db
    environment:
      POSTGRES_DB: saasflow
      POSTGRES_USER: saasflow_user
      POSTGRES_PASSWORD: saasflow_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
